// src/app/layout/footer/footer.component.ts
import { Component, OnInit } from '@angular/core'
import { environment as env } from '../../../environments/environment'

import { I18nService } from '../../core'

@Component({
  selector: 'ae-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent implements OnInit {

  languages: any
  currentLang: string

  constructor(private i18nService: I18nService) {}

  ngOnInit() {
    this.languages = env.LANGUAGES
    this.currentLang = this.i18nService.getCurrentLang() || this.i18nService.getDefaultLang()
    this.i18nService.getOnLangChange().subscribe((event) => {
      this.currentLang = event.lang
    })
  }

  changeLanguage(lang: string) {
    this.i18nService.changeLanguage(lang)
  }
}

<footer id="footer">
  <div class="container">
    <div class="row">
      <p class="ml-auto mr-2">© 2019 Artaeum</p>
      <div>
        <a class="dropdown-toggle" href="#" id="langdrop" data-toggle="dropdown">
          {{ languages[currentLang] }}
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" (click)="changeLanguage('en')">{{ languages['en'] }}</a>
          <a class="dropdown-item" (click)="changeLanguage('ru')">{{ languages['ru'] }}</a>
        </div>
      </div>
      <a id="footer-logo" class="mx-auto" routerLink="/">æ</a>
      <p class="mr-auto">Created by <a routerLink="/u/egor_repnikov">Egor Repnikov</a></p>
    </div>
  </div>
</footer>

// src/components/layout/Footer.svelte
<footer id="footer">
  <div class="container">
    <div class="row">
      <p class="ml-auto mr-2">© 2019 Artaeum</p>
      <div>
        <a
          class="dropdown-toggle"
          href="#"
          id="langdrop"
          data-toggle="dropdown">
          🇷🇺
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item">🇺🇸</a>
          <a class="dropdown-item">🇷🇺</a>
        </div>
      </div>
      <a id="footer-logo" class="mx-auto" href="/">æ</a>
      <p class="mr-auto">
        Created by
        <a href="/user/egor_repnikov">Egor Repnikov</a>
      </p>
    </div>
  </div>
</footer>
