// src/app/profile/subscribers/subscribers.component.ts
import { Component, OnInit } from '@angular/core'
import { ActivatedRoute } from '@angular/router'

import { UserService, User, SubscriptionService, Subscription } from '../../core'

@Component({
  selector: 'ae-subscribers',
  templateUrl: './subscribers.component.html'
})
export class SubscribersComponent implements OnInit {

  currentUser: User
  user: User
  subscriptions: Subscription[]
  subscribers: User[] = []
  page: any
  previousPage: any
  totalItems: any
  postsPerPage: number

  constructor(
    private userService: UserService,
    private subscriptionService: SubscriptionService,
    private activatedRoute: ActivatedRoute
  ) {}

  async ngOnInit() {
    const params = await this.activatedRoute.parent.params.toPromise()
    const { body } = await this.subscriptionService
      .query({ profileId: params['login'] })
      .toPromise()
    this.subscriptions = body
    this.loadUsers(body)
  }

  private async loadUsers(subs: Subscription[]) {
    for (const s of subs) {
      const { body } = await this.userService.get(s.subscriberId).toPromise()
      this.subscribers.push(body)
    }
  }
}

<div class="col-md-12 mx-auto">
  <div class="panel panel-default" *ngIf="subscribers.length > 0">
    <div class="panel-body">
      <div class="table-container">
        <table class="table-users table">
          <tbody>
            <tr *ngFor="let s of subscribers; let i = index">
              <td width="10">
                <img class="pull-left rounded-circle" width="50" [src]="subscriptions[i].id | imageAppender:'profile':'avatar'" onError="this.src = '/assets/ae.jpg'" />  
              </td>
              <td>
                <a [routerLink]="['/u', s.login]">@{{ s.login }}</a>
                <br>
                {{ s.firstName }} {{ s.lastName }}
              </td>
              <td>
                {{ 'profile.subscribers.subscribed-on' | translate }} {{ subscriptions[i].createdDate | dateConverter }}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="alert alert-dark font-weight-bold" role="alert" *ngIf="subscribers.length === 0">
    {{ 'profile.subscribers.no-subscribers' | translate }}
  </div>
</div>

// src/routes/user/[login]/subscribers.svelte
<script context="module">
  import { getUser, getSubscriptions } from '../../../api'

  export async function preload({ params: { login } }) {
    const profile = await getUser(login, this.fetch)
    const subscriptions = await getSubscriptions(`?profileId=${profile.id}`, this.fetch)
    for (const subscription of subscriptions) {
      subscription.profile = profile
      subscription.subscriber = await getUser(subscription.subscriberId, this.fetch)
    }
    return { login, subscriptions }
  }
</script>

<script>
  export let login
  export let subscriptions
</script>

<svelte:head>
  <title>@{login}'s subscribers - Artaeum</title>
</svelte:head>

<div class="row">
  <div class="col-md-6 mx-auto">
    {#if subscriptions.length > 0}
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="table-container">
            <table class="table-users table">
              <tbody>
                {#each subscriptions as s}
                  <tr>
                    <td width="10">
                      <img class="pull-left rounded-circle" width="50" src="/storage/profile/avatar/mock" onError="this.src = '/ae.jpg'" />  
                    </td>
                    <td>
                      <a href="/user/{s.subscriber.login}">@{s.subscriber.login}</a>
                      <br>
                      {s.subscriber.firstName} {s.subscriber.lastName}
                    </td>
                    <td>
                      subscribed on {s.createdDate}
                    </td>
                  </tr>
                {/each}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    {/if}
    {#if subscriptions.length === 0}
      <div class="alert alert-dark font-weight-bold" role="alert">
        User has no subscribers
      </div>
    {/if}
  </div>
</div>
